# Generated by Django 4.2.14 on 2024-07-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_education_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
