# Generated by Django 4.2.14 on 2024-08-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_experience_start_date_alter_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("tr", "Türkçe")],
                default="en",
                max_length=2,
            ),
        ),
    ]
