# Generated by Django 4.2.14 on 2024-08-08 18:20

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_profile_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverletter",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
