# Generated by Django 4.2.14 on 2024-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_coverletter_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverletter",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
