# Generated by Django 4.2.14 on 2024-08-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
