# Generated by Django 4.2.14 on 2024-07-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0002_translation_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Language Name"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="translation",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="language.languagetag",
                verbose_name="Language Tag",
            ),
        ),
    ]
